# Generated by Django 5.1.6 on 2025-02-24 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitTitle', models.CharField(max_length=100)),
                ('unitCode', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfTitle', models.CharField(max_length=100)),
                ('pdfFile', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('pdfDownloadLink', models.URLField(blank=True, null=True)),
                ('pdfPageCount', models.IntegerField()),
                ('pdfSize', models.IntegerField(help_text='Size in KB')),
                ('pdfDate', models.DateField(auto_now_add=True)),
                ('uploadedBy', models.CharField(blank=True, default='Anonymous', max_length=100, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='core.unitprofile')),
            ],
        ),
    ]
