# Generated by Django 5.1.6 on 2025-02-24 19:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpdf',
            name='pdfFile',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255, verbose_name='pdfs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unitpdf',
            name='pdfSize',
            field=models.IntegerField(blank=True, help_text='Size in KB'),
        ),
        migrations.AlterField(
            model_name='unitprofile',
            name='unitTitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
