# Generated by Django 5.1.6 on 2025-02-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_unitpdf_pdffile_alter_unitpdf_pdfsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpdf',
            name='pdfDownloadLink',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='unitpdf',
            name='pdfTitle',
            field=models.CharField(max_length=1000),
        ),
    ]
