# Generated by Django 5.1.6 on 2025-02-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_unitpdf_pdfdownloadlink_alter_unitpdf_pdftitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpdf',
            name='pdfPageCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
