# Generated by Django 5.1.6 on 2025-04-09 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_unitpdf_pdfpagecount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(db_index=True, help_text="The unit code (e.g., SMA191, UCU112). Should match the 'originalCode' if available.", max_length=50)),
                ('title', models.CharField(blank=True, help_text='The title of the unit (optional).', max_length=255, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Year of study (e.g., 1, 2, 3, 4).', null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2')], help_text='Semester (1 or 2).', null=True)),
                ('original_filename', models.CharField(help_text='The original filename as uploaded by the user.', max_length=255)),
                ('content_type', models.CharField(blank=True, help_text="The MIME type of the uploaded file (e.g., 'image/jpeg').", max_length=100, null=True)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('b2_file_path', models.CharField(db_index=True, help_text="The full path/object name of the file in the B2 bucket (e.g., 'exam_papers/SMA_191/uuid_xyz.jpg').", max_length=1024, unique=True)),
                ('b2_file_id', models.CharField(blank=True, help_text='The unique File ID assigned by Backblaze B2 upon upload.', max_length=100, null=True, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the paper was uploaded.')),
                ('uploader', models.ForeignKey(blank=True, help_text='The user who uploaded this paper (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
